import Navigation from '../components/Navigation'
import Footer from '../components/Footer'
import { AlertTriangle } from 'lucide-react'

const SECTIONS: Array<{ id: string; title: string; body: string[] }> = [
  {
    id: 'no-advice',
    title: 'Not Investment Advice',
    body: [
      'Verdexis is a portfolio analytics, market data, and educational platform. Nothing on the site, in the application, in newsletters, in chat, or generated by Verdexis AI constitutes investment, legal, tax, or accounting advice.',
      'You alone are responsible for evaluating the merits and risks of any investment decision. Consult a licensed financial professional before acting on any information presented.',
    ],
  },
  {
    id: 'risk',
    title: 'Risk Disclosure',
    body: [
      'All investments carry risk, including loss of principal. Cryptocurrency and digital assets are highly volatile and may experience extreme price swings, total loss of value, or extended illiquidity.',
      'Past performance is not indicative of future results. Backtests, simulated returns, and AI-generated projections are hypothetical and do not represent actual trading.',
      'Leverage, derivatives, and margin trading dramatically increase risk and may result in losses exceeding deposits.',
    ],
  },
  {
    id: 'data',
    title: 'Market Data Sources',
    body: [
      'Crypto prices are sourced from CoinGecko and Binance public APIs and may be delayed or temporarily unavailable.',
      'Equities and ETF data are sourced from Alpha Vantage and Finnhub. Quotes may be delayed by 15+ minutes depending on exchange and provider tier.',
      'News headlines are aggregated from third-party publishers; Verdexis does not author or endorse third-party content.',
      'Verdexis makes no warranty regarding the accuracy, completeness, or timeliness of any market data displayed.',
    ],
  },
  {
    id: 'ai',
    title: 'AI Output Disclosure',
    body: [
      'Verdexis AI uses large language models to summarise, analyse, and generate insight. Outputs may contain errors, omissions, or hallucinations.',
      'AI-generated portfolio commentary, sentiment analysis, and trade ideas are produced algorithmically and have not been reviewed by a human investment professional.',
      'You should independently verify any factual claim or numerical value before relying on it.',
    ],
  },
  {
    id: 'jurisdiction',
    title: 'Jurisdiction & Eligibility',
    body: [
      'Verdexis is not registered as a broker-dealer, investment adviser, FCM, or money services business in any jurisdiction.',
      'The platform is offered for general information purposes and may not be available or appropriate in your country. You are responsible for compliance with all local laws.',
      'Verdexis does not custody assets, execute trades on your behalf, or act as a fiduciary.',
    ],
  },
  {
    id: 'crypto-deposits',
    title: 'Crypto Deposits',
    body: [
      'Crypto deposits are made by sending funds to a deposit address displayed on the Wallet → Deposit screen for the selected currency. Each address is tied to a specific blockchain network; sending an asset on any other network is highly likely to result in permanent loss of those funds.',
      'Where the network requires a memo, destination tag, or similar identifier (e.g. XRP), it must be included exactly as displayed. Omitted or incorrect memos can cause irreversible loss.',
      'When you submit the on-chain transaction hash, Verdexis verifies the transaction directly against a public block explorer; once the network reaches the required number of confirmations, the deposit is credited to your wallet automatically. Deposits without a verified transaction hash, or for assets where automatic verification is not yet available, are queued for manual admin review. Large or first-time deposits may also be held briefly for compliance review.',
      'Verdexis does not impose a deposit fee, but the underlying network (gas, miner fee) is paid by the sender. Verdexis cannot reverse, refund, or recover crypto sent in error, to a wrong address, on the wrong network, or without a required memo.',
    ],
  },
  {
    id: 'fees',
    title: 'Fees & Charges',
    body: [
      'Trading fee: a flat 0.10% (10 basis points) is added to buys and deducted from sells. The fee is itemised in the order Review modal before you confirm.',
      'Account & management fee: funded accounts are subject to a recurring 0.4% monthly fee, calculated on the prevailing USD wallet balance and debited on the 26th of each calendar month. The debit is itemised in your transaction history.',
      'Withdrawal fees: bank (ACH / wire) withdrawals are free. Crypto withdrawals carry a Verdexis processing fee that scales with the withdrawal amount, plus the underlying blockchain network (gas) fee. The total is always shown for confirmation before submission.',
      'Deposit fees: free for both bank and crypto deposits. Network confirmation costs for incoming crypto are paid by the sender.',
      'No subscription fees: Verdexis is free to sign up and use. There are no monthly or annual plan fees — only the transparent trading, withdrawal and account-management fees described above.',
    ],
  },
  {
    id: 'affiliate',
    title: 'Affiliate & Partner Disclosure',
    body: [
      'Verdexis may receive referral compensation from exchanges, brokerages, or data providers featured on the platform. Compensation does not influence editorial content or AI output.',
      'When a partnership materially affects placement, it will be labelled “Sponsored” or “Partner”.',
    ],
  },
]

export default function Disclosures() {
  return (
    <div className="min-h-screen bg-[#070C0E]">
      <Navigation />
      <div className="pt-24 pb-16 px-6">
        <div className="max-w-[920px] mx-auto">
          <div className="flex items-center gap-3 text-xs uppercase tracking-[0.05em] text-amber-400 mb-3">
            <AlertTriangle className="w-3 h-3" /> Disclosures
          </div>
          <h1 className="text-4xl md:text-5xl font-light tracking-[-0.03em] text-[#E5E5E5] mb-4">
            Risk &amp; Regulatory Disclosures
          </h1>
          <p className="text-sm text-[#A0A0A0] mb-12">
            Read these disclosures carefully before using Verdexis. Last updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}.
          </p>

          {/* Quick nav */}
          <nav className="grid grid-cols-2 sm:grid-cols-3 gap-2 mb-12 p-4 rounded-2xl bg-[#0f1619]/50 border border-[#ffffff08]">
            {SECTIONS.map((s) => (
              <a key={s.id} href={`#${s.id}`} className="text-xs text-[#A0A0A0] hover:text-[#0C8B44] transition-colors">
                {s.title}
              </a>
            ))}
          </nav>

          {SECTIONS.map((s) => (
            <section key={s.id} id={s.id} className="mb-12 scroll-mt-24">
              <h2 className="text-2xl font-light text-[#E5E5E5] mb-4">{s.title}</h2>
              <div className="space-y-3">
                {s.body.map((p, i) => (
                  <p key={i} className="text-sm text-[#A0A0A0] leading-relaxed">{p}</p>
                ))}
              </div>
            </section>
          ))}

          <div className="mt-16 p-5 rounded-2xl bg-amber-400/5 border border-amber-400/20">
            <p className="text-xs text-amber-200/90 leading-relaxed">
              By continuing to use Verdexis you acknowledge that you have read, understood, and accept these disclosures.
              Questions? Email <a href="mailto:legal@verdexis.com" className="underline">legal@verdexis.com</a>.
            </p>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}
